### ISSUE TITLE
Help Behaviour is Inconsistent

### ISSUE THREAD

**Issue by halfSpinDoctor** [spinicist/QUIT#1]
For most qi binaries, if you do not supply any input arguments it will default to showing the help message (-h option). This is true for:

qiafi, qidespot1, qidespot1hifi, qidespot2, qimultiecho, qinewimage, qissfpbands, qiunwrap

For qicomplex without any input arguments, the program terminates with an uncaught exception:
"Invalid combination of input specifiers."

For qidespot2fm without any input arguments, the program exits successfully with an error message:
"Wrong number of arguments. Need a T1 map and one SSFP file."

For qimcdespot and qisignal, the program prompts for some input.

It would be good if this behavior were standardised, i.e. if no input arguments are specified, the program automatically defaults to the -h option to show the help message.

It would also be good for qicomplex if an error message was generated (as in qidespot2fm) instead of throwing an exception.

**Comment by spinicist** [comment]
This should be all fixed in the development branch, please test and confirm.

qimcdespot and qisignal don't take any arguments, only options, so displaying the usage by default doesn't make sense. Instead I added a one line message saying to use the -h option if people want the usage.

qicomplex has been rewritten with a more intuitive usage (I hope). Comments are welcome. It was written in a hurry when I discovered a bug in fslcomplex - it corrupts image headers with certain command line options.

**Comment by halfSpinDoctor** [comment]
Development branch fails to build (using easy_build.sh) with the following error:
```bash
CMake Error: File /Users/shurley/Software/QMRI/QUIT/Test/test_mcdespot.sh does not exist.
CMake Error at CMakeLists.txt:40 (configure_file):
  configure_file Problem configuring file


-- Configuring incomplete, errors occurred!
See also "/Users/shurley/Software/QMRI/QUIT/Build/CMakeFiles/CMakeOutput.log".
```

**Comment by spinicist** [comment]
Sorry, I committed a separate change prematurely. Please try again.

I assume you have cloned the repo? You only need to run easy_build once, after that you can just run make -j in the /Build directory, even after a git pull.

**Comment by halfSpinDoctor** [comment]
Looks good now.

Yes the repo is cloned, and use git pull to update. Tried make first, but when it failed thought I should delete Build/ and try again from the beginning to make sure it wasn't because of bad configuration.

**Comment by spinicist** [comment]
Merged to master now, closing.
