### ISSUE TITLE
residuals / feature request 

### ISSUE THREAD

**Issue by ravenep** [spinicist/QUIT#16]
Would it be possible to add residual maps for `qimultiecho` ? I saw a few other qi-scripts had this already. Cheers!

**Comment by spinicist** [comment]
Good point. I have added it to my to-do list.

**Comment by spinicist** [comment]
Hi,

this has now been implemented in the [mt branch](https://github.com/spinicist/QUIT/tree/mt). However, I have ended up moving to ITK 5 and C++17, so I suggest doing a fresh clone of the repository and running the `build.sh` script (used to be called `easy_build.sh`). On Mac you should be fine with the system compiler, on Linux you will need GCC 7.

I will be merging the `mt` branch into `development` soon, and making a `2.1` release as soon as ITK 5 is officially released (unknown when).

I'll close this issue for now.

**Comment by ravenep** [comment]
Thanks @spinicist - this worked for me. To confirm, I got a total residual map & also a map for each echo using --resids 

:+1: :+1:
