### ISSUE TITLE
--clampT2 typo in qimultiecho 

### ISSUE THREAD

**Issue by emilljungberg** [spinicist/QUIT#17]
Typo in the long format option in `qimultiecho` for clamping T2

```
-p[CLAMP T2], --clampPD=[CLAMP T2]     Clamp T2 between 0 and value
```

Should be
```
-p[CLAMP T2], --clampT2=[CLAMP T2]     Clamp T2 between 0 and value
```

**Comment by spinicist** [comment]
This option has disappeared in the `mt` branch, as `qimultiecho` was heavily re-written. This will be merged to `development` in the near future.
