### ISSUE TITLE
multi-compartment with limit FA & CPMG sequence 

### ISSUE THREAD

**Issue by miladseyfi** [spinicist/QUIT#20]
Hello dear 
Unfortunately, I've acquired my whole data with only two flip angles (in both SPGR & bSSFP); My question is can I use qimcdespot?
Another thing; I also have Multi Echo Spin Echo data with different 10 TEs; I've taken a look at the documentation but couldn't find the multi-compartment model for this kind of sequence.
this is all I have and WMF is completely needed for my thesis. 
I would appreciate a reply at your earliest convenience.

**Comment by spinicist** [comment]
Hello,

Sadly I don't think I can help very much.

You cannot run the mcDESPOT model with only two flip-angles. You can calculate T1&T2 though.

I have not implemented the MESE MWF methods. These are complicated and we do not currently use them at our site, so I have not had any need to.

Best wishes and good luck,
Toby
