### ISSUE TITLE
error while running qidespot2 

### ISSUE THREAD

**Issue by miladseyfi** [spinicist/QUIT#21]
Hello, dear developer 
I've created T1 map from 2 repeatedly acquired SPGR images with different FA(4,18) using qidespot 1 .after that when I tried to produce T2 map I faced this error : 

terminate called after throwing an instance of 'itk::ExceptionObject'
  what():  ../External/ITK/Modules/Core/Common/include/itkImageToImageFilter.hxx:241:
itk::ERROR: ApplyAlgorithmFilter(0x2831bd0): Inputs do not occupy the same physical space! 

could you please help me with this error ?? 
bssfp images are acquired with 15 and 52 different FAs and whole scans TR is 8.9 ms.
I will send one of my data for you for speeding up finding the problem. 
thanks a lot.

**Comment by spinicist** [comment]
Hello,

This message occurs when images have differing voxel/matrix size or orientation. What preprocessing steps do you run? What is the output of `qihdr` on the inputs to `qidespot2`, i.e. the T1 map and your merged SSFP files?

**Comment by miladseyfi** [comment]
I registered all input file with a mprage T1 image and the qidespot2 run without any errors.
But the T1 and T2 maps seem strange. the T1 value of voxels is not logic. the max T1 value is  5.1141246e+04 and in T2 map there are negative values !!!!
May I send you the maps to take look at it ?? maybe I've run it incorrectly. 
(I've sent the data mentioned in the previous message to this email address: tobias.wood@kcl.ac.uk )

**Comment by spinicist** [comment]
Registering with an MPRAGE image is likely not optimal - if the MPRAGE is higher resolution than the DESPOT data you will end up performing a lot of unnecessary calculations. I usually register to one of the SPGR images.

Did you generate a brain mask before processing? If you don't pass a brain mask, then background voxels will have random noise in them.

**Comment by miladseyfi** [comment]
thank you dear for the quick reply 
I'll do as you said.
best regards
