### ISSUE TITLE
qi_lorentzian JSON file

### ISSUE THREAD

**Issue by eugenegkim** [spinicist/QUIT#22]
I tried running qi_lorentzian but got this error:
Error Missing JSON member: Lorentz

The documentation gives an example JSON file with only "freq" defined. What else has to go in the JSON file?

Thanks

**Comment by spinicist** [comment]
Hi,

I expanded the functionality of `qi_lorentzian` significantly earlier this year but forgot to update the documentation. I have now done so, hopefully https://quit.readthedocs.io/en/latest/Docs/MT.html#qi-lorentzian should update shortly.

In short you can now choose how many Lorentzians you want to fit. If you are trying to do WASSR then you only need one.

**Comment by eugenegkim** [comment]
Thanks, the documentation has updated, but I still get the same error. I'm
using the QUIT module on the NaN. I suppose that version expects different
inputs to the most recent stable release?

**Comment by eugenegkim** [comment]
It's working now, thanks!
