### ISSUE TITLE
documentation improvement: glibc version

### ISSUE THREAD

**Issue by seareel** [spinicist/QUIT#23]
A suggestion for improving the main README.md

in the **installation** section, some part reads:
> The Linux binaries are built with Ubuntu 14.04 with GCC 6. If you need to run on an older version of Linux with a previous version of glibc then you will need to compile from source.

The version of glibc is not specifically mentioned, just the distro and compiler version. Adding the glibc version corresponding to Ubuntu 14.04 would make the version limitation clearer, in particular if someone is using another distribution with a different glibc schedule. I believe Ubuntu 14.04 shipped with glibc 2.19.

Thanks for the great code !

**Comment by spinicist** [comment]
Hello,

I have finally found time to fix the CI builds and update a lot of things. There are new pre-built binaries available on the releases page, which are now built with Ubuntu 16.04 and I think glibc 2.3 - to be honest, trying to decipher the output of `readelf` and `ldd` is right at the edge of my understanding. I have made a note in the README about the glibc version. I will finally close this issue, feel free to re-open it or make any new ones if you find a problem.
