### ISSUE TITLE
CEST?

### ISSUE THREAD

**Issue by mathieuboudreau** [spinicist/QUIT#24]
Hi Toby,

You mention in your documentation that QUIT some basic CEST functionality,

https://quit.readthedocs.io/en/latest/Docs/MT.html

and I can see that in your code history you do in fact have files referencing CEST,

https://github.com/spinicist/QUIT/blob/9cd2e8e08ea9c981cb36fc78dccb565e2cdc92ee/Source/QI/Algorithms/CEST.cpp .

However I can't seem to find CEST-related functions/command line interfaces in the current master branch. Is the documentation out of date and CEST is no longer supported, or am I not looking in the right place (maybe the lineshape/z-spectrum commands are those related to CEST)?

Thanks!

**Comment by spinicist** [comment]
Hi,
I should update that intro paragraph! You're looking for `qi_zspec_interp` and `qi_lorentzian`. I have an example `nipype` workflow I should upload as well.

**Comment by mathieuboudreau** [comment]
Great - thanks for clarifying!

**Comment by spinicist** [comment]
Hi,
I've added the example workflow to the repo. This exact one is untested as I don't have the necessary data with me right now. Docs are also slightly tweaked, I'm waiting for readthedocs to pick up the changes. I'm going to mark this issue closed, any other questions please re-open it.
