### ISSUE TITLE
Re: compiling

### ISSUE THREAD

**Issue by nmskhan** [spinicist/QUIT#31]
Hi
I was trying to install qi for Mac, I was able to install precompiled executables and run qi. Unfortunately, qimask was missing in those libraries. So, I wanted to reinstall qi by compiling from source, by running .build.sh. I do not see build.sh in this tar package. Wondering that how to fix that? Please let me know. Thanks
Ned

**Comment by spinicist** [comment]
Hello,

Are you sure mask is missing? The command is `qi mask`, note the space between `qi` and `mask`.

The compile command is now `bootstrap.sh`, and it will take care of all dependencies via `vcpkg`. I need to update the developer documentation.

**Comment by nmskhan** [comment]
Hello Tobias
Yes it is a qi mask instead of qimask, Sorry little confused. I was able to install it. Thanks
Ned

**Comment by spinicist** [comment]
Great! Thanks for letting me know.
