### ISSUE TITLE
'holes' in qmt output 

### ISSUE THREAD

**Issue by CarolynMcNabb** [spinicist/QUIT#33]
Dear @spinicist,

We've been using the quit qmt function to analyse some of our magnetisation transfer data from two different scanners (a Siemens Connectom and a Siemens Prisma). We're running into an issue whereby some voxels inside the brain are exhibiting incredibly small (but not zero) values (e.g. for the QMT_f_b image, all the dark voxels have the value 9.999999974752427e-7). These voxels are often within the white matter, so it's not a masking problem or anything like that. The number of iterations for these voxels is relatively low (below 10) so I don't think it's necessarily a convergence issue either - though I could be wrong. I've included an image below so you can see what I'm talking about. Importantly, the images that we are using as input do not have holes in these locations.

I'm running the command as follows:
```
${software_dir}/qi qmt --verbose ${qMT_dir}/${id}_qMT_merged_mcf_biascorrected.nii.gz --T1 ${qMT_dir}/${id}_D1_T1.nii.gz --mask ${qMT_dir}/${id}_maskResample_mcf.nii.gz --lineshape ${json_dir}/superlorentz.json --B1 ${qMT_dir}/${id}_POLY_B1.nii --f0 ${qMT_dir}/${id}_FM_f0.nii.gz --out ${qMT_dir}/${id}_ < ${json_dir}/WANDQMT_3TM.json
```

Any advice you have would be very much appreciated!

Kind regards,
Carolyn McNabb

![Screenshot from 2022-12-05 14-47-11](https://user-images.githubusercontent.com/58777305/205668371-01902b81-e3ae-4725-9dd6-9d27bd83539c.png)

**Comment by spinicist** [comment]
Hello,

What do your input B1, f0 & T1 maps look like for this subject?

**Comment by CarolynMcNabb** [comment]
Thanks for you super quick response! 
B1 looks like this:
![Screenshot from 2022-12-05 15-20-37](https://user-images.githubusercontent.com/58777305/205674410-9e5ebe91-81fd-4d7d-a466-b66ca0960955.png)
f0 like this:
![Screenshot from 2022-12-05 15-20-49](https://user-images.githubusercontent.com/58777305/205674491-f6aeee49-e38b-4f63-bd0a-694a02718f12.png)
and T1 like this:
![Screenshot from 2022-12-05 15-20-58](https://user-images.githubusercontent.com/58777305/205674531-327623d3-b8b5-4cde-87e7-5509d7e242f2.png)

**Comment by spinicist** [comment]
Okay, those all look reasonable. Are you able to share the full dataset via Dropbox or similar (you can direct it to my work e-mail)?

**Comment by CarolynMcNabb** [comment]
Thanks @spinicist - I've created a OneDrive folder and shared it with your work email address.

**Comment by spinicist** [comment]
This was discussed via e-mail and is not a problem with QUIT, so closing the issue here.
