### ISSUE TITLE
Contribute to QUIT

### ISSUE THREAD

**Issue by jeremie-fouquet** [spinicist/QUIT#36]
Hello,

We are using QUIT to process multi-parameter mapping (MPM) mouse brain data at the Douglas Cerebral Imaging Centre with @gdevenyi. We would like to contribute and suggest a few changes to the toolbox. Does [CONTRIBUTING.md](https://github.com/spinicist/QUIT/blob/28d6a8e2e739c95ea7d0084b0d1b9959eb62264a/CONTRIBUTING.md) still describe the preferred method, or can we use a "one issue, one branch per contribution" approach? (AKA a [forking + feature branching workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow).)

Thank you.

**Comment by spinicist** [comment]
Hello,

CONTRIBUTING.md is very out of date (except the Code of Conduct. That bit is fine). I had forgotten it had existed. The development branch mentioned no longer exists, and I haven't follow the "git flow" method for a very long time.

Please follow standard practice of creating issues + pull requests branched from master, as you have described.

If you have the time to contribute a change to CONTRIBUTING.md, all the better!

I look forward to the Pull Requests.

**Comment by jeremie-fouquet** [comment]
Ok, let's start with this as a test :smiley:.
