### ISSUE TITLE
Clarification on MP2RAGE Implementaiton/Usage

### ISSUE THREAD

**Issue by gdevenyi** [spinicist/QUIT#37]
Reading over the MP2RAGE details:
https://quit.readthedocs.io/en/latest/Docs/Relaxometry.html#qi-mp2rage

Its not clear to me what inputs are expected. Under our standard Siemens sequence we get out INV1, INV2 and UNI.

I'd like to get out a robust (denoised) T1-weighted image and the T1 map, can this function do this, or is it expecting some sort of raw data?

**Comment by gdevenyi** [comment]
Okay, I was thinking of the robustcombination ( https://github.com/marcpabst/mp2rage-denoise/blob/master/mp2rage_denoise.py ) method for already-reconstructed UNIs with non-complex INV1 and INV2 images already processed by the scanner. Thanks.

**Comment by spinicist** [comment]
`qi mp2rage` already has the robust combination method implemented (and it's documented https://quit.readthedocs.io/en/latest/Docs/Relaxometry.html#qi-mp2rage !) with full control over the regularization parameter. Hence it needs the raw data as input.
