### ISSUE TITLE
Documentation References

### ISSUE THREAD

**Issue by AndrewLawrence** [spinicist/QUIT#8]
Many of the references in the documentation (http://spinicist.github.io/QUIT/) for the relaxometry module point to the same link for the DREAM citation: https://onlinelibrary.wiley.com/doi/abs/10.1002/mrm.24158

Looking at the raw I think this is because the citation references are resolved per-markdown document rather than per-section. The link for citation [1] is overwritten each section with the last definition of [1] pointing to the DREAM paper.

Could fix with \[text\]\(link\) format for each citation or do consecutive numbering of citations for the whole document.

**Comment by spinicist** [comment]
Thanks for bringing this to my attention, all the links should now be fixed. Please re-open if you find one that doesn't work.
